<a href="https://colab.research.google.com/github/Karthikaddagadderamesh/thesis/blob/main/PlaneRCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
!nvidia-smi
!cat /etc/*-release
!gcc --version
!nvcc --version

Tue Nov 10 09:17:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [25]:
!apt update -qq;
!wget https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb; 11
!dpkg -i cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb;
!apt-key add /var/cuda-repo-8-0-local-ga2/7fa2af80.pub;
!apt-get update -qq;
!apt-get install cuda gcc-5 g+±5 -y -qq;
!ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc;
!ln -s /usr/bin/g+±5 /usr/local/cuda/bin/g++;
!apt install cuda-8.0;

28 packages can be upgraded. Run 'apt list --upgradable' to see them.
--2020-11-10 09:12:33--  https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
Resolving developer.nvidia.com (developer.nvidia.com)... 152.199.0.24
Connecting to developer.nvidia.com (developer.nvidia.com)|152.199.0.24|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://developer.download.nvidia.com/compute/cuda/8.0/secure/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb?gWbuLq4fJy2r8LQVk44eMkQ9gOJFa3gVLBkhjibJoR3ELL5ut_IHk8oSP-mbQ0WCQh89QII12LZgV4HpFULoQf0w33JlILZUqkftp22krL2UN1QKQreqM9_C1mlviSjplaNRQkRuUpNtaobbi44GVpNQDsWTU_7JVhcEffaWO9am9SlqfFm5g3Bdq9i_T6kwjZeuBZjyny9PcoM9eCsHRmmiOg [following]
--2020-11-10 09:12:33--  https://developer.download.nvidia.com/compute/cuda/8.0/secure/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb?gWbuLq4fJy2r8LQVk44eMkQ9gOJF

In [26]:
!nvcc --version
!gcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



In [9]:
!pip install torch==0.4.0


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     |████████████████████████████████| 484.0MB 33kB/s 
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.4.0 which is incompatible.
ERROR: fastai 1.0.61 has requirement torch>=1.0.0, but you'll have torch 0.4.0 which is incompatible.
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101


In [12]:
!pip list

Package                       Version        
----------------------------- ---------------
absl-py                       0.10.0         
alabaster                     0.7.12         
albumentations                0.1.12         
altair                        4.1.0          
argon2-cffi                   20.1.0         
asgiref                       3.3.0          
astor                         0.8.1          
astropy                       4.1            
astunparse                    1.6.3          
async-generator               1.10           
atari-py                      0.2.6          
atomicwrites                  1.4.0          
attrs                         20.2.0         
audioread                     2.1.9          
autograd                      1.3            
Babel                         2.8.0          
backcall                      0.2.0          
beautifulsoup4                4.6.3          
bleach                        3.2.1          
blis                          0.4.

In [13]:
!git clone https://github.com/NVlabs/planercnn.git

fatal: destination path 'planercnn' already exists and is not an empty directory.


In [14]:
!pwd
!ls
%cd planercnn/



/content
cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb  planercnn
drive						       sample_data
/content/planercnn


In [15]:
pip install -r requirements.txt

     |████████████████████████████████| 430kB 5.5MB/s 
     |████████████████████████████████| 13.9MB 240kB/s 
     |████████████████████████████████| 25.4MB 120kB/s 
     |████████████████████████████████| 25.3MB 1.3MB/s 
     |████████████████████████████████| 519.5MB 30kB/s 
     |████████████████████████████████| 51kB 8.1MB/s 
ERROR: umap-learn 0.4.6 has requirement numpy>=1.17, but you'll have numpy 1.15.4 which is incompatible.
ERROR: torchvision 0.8.1+cu101 has requirement torch==1.7.0, but you'll have torch 0.4.1 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.15.4 which is incompatible.
ERROR: spacy 2.2.4 has requirement tqdm<5.0.0,>=4.38.0, but you'll have tqdm 4.28.1 which is incompatible.
ERROR: rpy2 3.2.7 has requirement cffi>=1.13.1, but you'll have cffi 1.11.5 which is incompatible.
ERROR: plotnine 0.6.0 has requirement numpy>=1.16.0, but you'll have numpy 1.15.4 which is incompatible.
ERROR: fbprophet 0.7.1 h

In [27]:
!/usr/local/cuda/bin/nvcc --version
!nvidia-smi

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
Tue Nov 10 09:15:10 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.38       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+---

In [18]:
#!gcc --version
# Remove old packages and install new ones
#!sudo apt-get remove gcc g++
#!sudo apt-get install gcc-4.8 g++-4.8 build-essential
# After this however, you can only access it with specifically calling for 'gcc-4.8' and 'g++-4.8'. So we set them default
#!sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 10
#!sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 10
#!sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
#!sudo update-alternatives --set cc /usr/bin/gcc
#!sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
#!sudo update-alternatives --set c++ /usr/bin/g++
#!gcc --version

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cpp cuda-cublas-8-0 cuda-cublas-dev-8-0 cuda-cudart-8-0 cuda-cudart-dev-8-0
  cuda-cufft-8-0 cuda-cufft-dev-8-0 cuda-cuobjdump-10-0 cuda-cuobjdump-10-1
  cuda-curand-8-0 cuda-curand-dev-8-0 cuda-cusolver-8-0 cuda-cusolver-dev-8-0
  cuda-cusparse-8-0 cuda-cusparse-dev-8-0 cuda-driver-dev-8-0 cuda-gdb-10-0
  cuda-gdb-10-1 cuda-gpu-library-advisor-10-0 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-0 cuda-license-8-0 cuda-memcheck-10-0 cuda-memcheck-10-1
  cuda-misc-headers-8-0 cuda-npp-8-0 cuda-npp-dev-8-0 cuda-nsight-10-0
  cuda-nsight-10-1 cuda-nsight-compute-10-0 cuda-n

In [28]:
!sudo rm /usr/local/cuda/bin/gcc
!sudo rm /usr/local/cuda/bin/g++
!sudo apt install gcc-5 g++-5
!sudo ln -s /usr/bin/gcc-5 /usr/local/cuda/bin/gcc
!sudo ln -s /usr/bin/g++-5 /usr/local/cuda/bin/g++

rm: cannot remove '/usr/local/cuda/bin/gcc': No such file or directory
rm: cannot remove '/usr/local/cuda/bin/g++': No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-5 is already the newest version (5.5.0-12ubuntu1).
gcc-5 is already the newest version (5.5.0-12ubuntu1).
The following packages were automatically installed and are no longer required:
  cuda-cuobjdump-10-0 cuda-cuobjdump-10-1 cuda-gdb-10-0 cuda-gdb-10-1
  cuda-gpu-library-advisor-10-0 cuda-gpu-library-advisor-10-1
  cuda-libraries-10-0 cuda-memcheck-10-0 cuda-memcheck-10-1 cuda-nsight-10-0
  cuda-nsight-10-1 cuda-nsight-compute-10-0 cuda-nsight-compute-10-1
  cuda-nsight-systems-10-1 cuda-nvdisasm-10-0 cuda-nvdisasm-10-1
  cuda-nvml-dev-10-0 cuda-nvprof-10-0 cuda-nvprune-10-0 cuda-nvprune-10-1
  cuda-nvtx-10-0 cuda-nvvp-10-0 cuda-nvvp-10-1 cuda-sanitizer-api-10-1
  cuda-visual-tools-10-0 cuda-visual-tools-10-1 gfortran-7 libbz2-dev
  libgfortran-

In [29]:
!nvcc --version
!gcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
gcc (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



In [31]:
!pwd
%cd nms/src/cuda/
!nvcc -c -o nms_kernel.cu.o nms_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_37


/content/planercnn
/content/planercnn/nms/src/cuda


In [34]:
%cd ../../
!python build.py
%cd ../

/content/planercnn/nms
Including CUDA code.
/content/planercnn/nms
generating /tmp/tmpb0ymvzsq/_nms.c
setting the current directory to '/tmp/tmpb0ymvzsq'
running build_ext
building '_nms' extension
creating content
creating content/planercnn
creating content/planercnn/nms
creating content/planercnn/nms/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c _nms.c -o ./_nms.o -std=c99
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.6/dist-pac

In [36]:
%cd roialign/roi_align/src/cuda/
!nvcc -c -o crop_and_resize_kernel.cu.o crop_and_resize_kernel.cu -x cu -Xcompiler -fPIC -arch=sm_37
%cd ../../


/content/planercnn/roialign/roi_align/src/cuda
/content/planercnn/roialign/roi_align


In [37]:
!python build.py
%cd ../../

Including CUDA code.
/content/planercnn/roialign/roi_align
generating /tmp/tmp3z5264rr/_crop_and_resize.c
setting the current directory to '/tmp/tmp3z5264rr'
running build_ext
building '_crop_and_resize' extension
creating content
creating content/planercnn
creating content/planercnn/roialign
creating content/planercnn/roialign/roi_align
creating content/planercnn/roialign/roi_align/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c _crop_and_resize.c -o ./_crop_and_resize.o -std=c99 -fopenmp -std=c99
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-s

In [38]:
!pwd


/content/planercnn


In [39]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving checkpoint.pth to checkpoint.pth
Saving checkpoint_refine.pth to checkpoint_refine.pth
User uploaded file "checkpoint.pth" with length 278796562 bytes
User uploaded file "checkpoint_refine.pth" with length 3940939 bytes


In [40]:
!pwd
!ls

/content/planercnn
anchors						       LICENSE.md
carla_image					       models
checkpoint					       nms
config.py					       options.py
cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb  plane_utils.py
data_prep					       README.md
datasets					       requirements.txt
evaluate.py					       roialign
evaluate_utils.py				       train_planercnn.py
example_images					       utils.py
Fisheye_image					       visualize_utils.py


In [79]:
!python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=example_images

the number of images 3
  0% 0/3 [00:00<?, ?it/s]/content/planercnn/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify al

In [44]:
!python evaluate.py --methods=f --suffix=warping_refine --dataset=inference --customDataFolder=Fisheye_image


the number of images 5
  0% 0/5 [00:00<?, ?it/s]/content/planercnn/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
rm: cannot remove 'test/inference/*_final.png': No such file or directory
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode

In [46]:
!python evaluate.py --methods=f --suffix=warping_refine --dataset=inference_1 --customDataFolder=carla_image

the number of images 5
  0% 0/5 [00:00<?, ?it/s]/content/planercnn/models/model.py:1473: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight)
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify al

# New Section

In [88]:
import numpy as np
data = np.load('/content/planercnn/test/inference/10_plane_parameters_0.npy')
print(data)

[[ 0.04641841  0.23571718 -0.63109964]
 [-0.3218502   2.3399358  -0.01789427]
 [ 0.19078982  0.40837577 -0.81829333]
 [ 0.13897687  2.086711    0.36237758]
 [-0.7394917   0.5580696   0.0082204 ]
 [ 0.18447663  1.2934539   0.81115055]]


In [1]:
!lsb_release --version


No LSB modules are available.


In [5]:
!pwd
%cd /content/


/content
/content


In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
!cp -r <PATH_TO_PNG_FOLDER> /content/gdrive/My Drive/